"""Public API for the project cognition runtime foundation."""

from .diff import build_diff_impact_payload
from .discovery import discover_reference_projects
from .db import (
    connect_cognition_db,
    cognition_transaction,
    ensure_cognition_db,
    get_active_generation_id,
    seed_active_generation,
)
from .paths import (
    cognition_db_path,
    cognition_dir,
    cognition_status_path,
    coverage_path,
    evidence_dir,
    graph_claims_path,
    graph_conflicts_path,
    graph_dir,
    graph_edges_path,
    graph_nodes_path,
    graph_slices_dir,
    graph_updates_path,
    provisional_dir,
    provisional_edges_path,
    provisional_nodes_path,
    provisional_observations_path,
)
from .reference_read import ReferenceProjectReadError, read_reference_project_cognition
from .schema import (
    ClaimRecord,
    ConflictRecord,
    EvidenceRecord,
    GraphEdge,
    GraphNode,
    ObservationRecord,
    SliceRecord,
    UpdateEventRecord,
)
from .status import CognitionStatus, read_cognition_status, write_cognition_status
from .store import (
    ensure_cognition_runtime_dirs,
    read_json_artifact,
    write_coverage,
    write_graph_claims,
    write_graph_conflicts,
    write_graph_edges,
    write_graph_nodes,
    write_graph_updates,
    write_json_artifact,
    write_slice,
)

__all__ = [
    "ClaimRecord",
    "CognitionStatus",
    "ConflictRecord",
    "EvidenceRecord",
    "GraphEdge",
    "GraphNode",
    "ObservationRecord",
    "SliceRecord",
    "UpdateEventRecord",
    "build_diff_impact_payload",
    "cognition_db_path",
    "cognition_dir",
    "cognition_status_path",
    "cognition_transaction",
    "connect_cognition_db",
    "coverage_path",
    "discover_reference_projects",
    "ensure_cognition_db",
    "ensure_cognition_runtime_dirs",
    "evidence_dir",
    "graph_claims_path",
    "graph_conflicts_path",
    "graph_dir",
    "graph_edges_path",
    "graph_nodes_path",
    "graph_slices_dir",
    "graph_updates_path",
    "get_active_generation_id",
    "provisional_dir",
    "provisional_edges_path",
    "provisional_nodes_path",
    "provisional_observations_path",
    "read_cognition_status",
    "read_reference_project_cognition",
    "read_json_artifact",
    "ReferenceProjectReadError",
    "seed_active_generation",
    "write_cognition_status",
    "write_coverage",
    "write_graph_claims",
    "write_graph_conflicts",
    "write_graph_edges",
    "write_graph_nodes",
    "write_graph_updates",
    "write_json_artifact",
    "write_slice",
]
